#!/bin/bash
GDBBATCH=$(mktemp -u)
OBJFILE=$(mktemp -u)
OPCODES=$(cat -)
echo 'set disassembly-flavor intel\ndisassemble /r b' > $GDBBATCH
echo "char b[] = { $OPCODES };" | gcc -g -w -x c -c -o $OBJFILE -
gdb $OBJFILE -batch -x $GDBBATCH | head -n -1 | tail -n +2 | cut -d':' -f2
